name: om_dbt_project
profile: om_dbt_project
version: '1.0.0'
config-version: 2

models:
  om_dbt_project:
    +materialized: view

    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: marts